### ISSUE TITLE
[Bug]: Quests disappear completely

### ISSUE THREAD

**Issue by loosegasket** [terrarium-earth/hercules#106]
### Bug Description

Was entering a biome type for a quest using the in-game editor. The game froze, I accidently clicked it and got [this error.](https://pastebin.com/xivcgQPz)

Now my quest screen is empty: 
![2023-10-17_18 28 36](https://github.com/terrarium-earth/Heracles/assets/148296689/9ebdb261-fa56-4b43-aad6-a3878af63f23)

My groups.txt looks like this: 
![groupscontents](https://github.com/terrarium-earth/Heracles/assets/148296689/8a0c01b5-60f3-4d07-b8cc-4f7891754124)

My quests folder looks like this: 
![questfoldercontents](https://github.com/terrarium-earth/Heracles/assets/148296689/99176c06-b823-4aec-83a3-e97c329747d2)

The /reload command does not help, often fails.

### How to Reproduce?

Using the in-game quest editor, make several groups and quests with four groups empty (no quests.) Make a biome quest. Insert biome ID or translation ID into the UI. Press enter. The game will freeze and either remain frozen until force-closed with no crash report or clicked on, producing a crash with the linked report.

I was unable to reproduce the bug reliably.

### Version

1.0.5

### Mod Loader Version

27.2.1

### Mod Loader

Forge

### Logs or additional context

[latest.log](https://github.com/terrarium-earth/Heracles/files/12974533/latest.log)
[crash-2023-10-17_02.18.52-client.txt](https://github.com/terrarium-earth/Heracles/files/12974538/crash-2023-10-17_02.18.52-client.txt)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by MythicHH** [comment]
I get this issue as well except I just went to bed and they disappeared.

**Comment by PirateSee** [comment]
I have the same issue, it started after saving and exiting once and the quests haven't came back since.

**Comment by ThatGravyBoat** [comment]
are you also on forge?

**Comment by ThatGravyBoat** [comment]
also if you run /reload they should get resent, it seems to be an issue where on forge it doesnt accept my packet, your quests still exist in the file system its just they didnt get sent to the client

**Comment by PirateSee** [comment]
yes im on forge
ah reloading does fix it, thanks!

**Comment by ThatGravyBoat** [comment]
ill look into more rn to see whats up so I can fix it
