### ISSUE TITLE
[Feature Request]: Option to remove quest dependency arrows

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [terrarium-earth/hercules#108]
### Is your feature request related to a problem?

quest dependency arrows can ruin some final quest line completion quests or quests you want to hang seporate from the rest, but still have a dependency

### Solution(s)

option in the quest options to disable arrow(s) leading toward it

### Mod Version

1.0.5

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
Already implemented in dev
