### ISSUE TITLE
[Feature Request]: NBT for Icon Selection, Reward Selection, Task Selection

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [terrarium-earth/hercules#110]
### Is your feature request related to a problem?

I cant set NBT for Icon Selection, and i can only set NBT for Reward Selection, Task Selection in a very inefficient way

### Solution(s)

allow us to input a string of the item with nbt in the same format as we would when using the /give command, right into the item text box when looking for item(s) for the three locations

### Mod Version

1.0.5

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
Icon selection you can just give yourself the item with the nbt and then in the top right click the little folder it will change it to inventory mode then you can select the item from there

**Comment by Kazuhiko-Gushiken** [comment]
@ThatGravyBoat when I look at what it shows in my inventory, it doesn't show the specific patchouli book with specific nbt. I has the Ruinic Grimore and The Shadow Chronicle which are both patchouli nbt based guidebooks but the texture of the base guidebook is all that showed

**Comment by Kazuhiko-Gushiken** [comment]
![image](https://github.com/terrarium-earth/Heracles/assets/132615999/01643bdc-796d-4bd1-b2d5-25be69a5cedb)
![image](https://github.com/terrarium-earth/Heracles/assets/132615999/1e436725-f2a1-4850-a320-07a88c21d95b)
