### ISSUE TITLE
[Feature Request]: More shapes/sizes for the icon background to let milestone quests pop more

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [terrarium-earth/hercules#112]
### Is your feature request related to a problem?

i cant give more character to the quests

### Solution(s)

add More shapes/sizes for the icon background to let milestone quests pop more

### Mod Version

1.0.5

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
You can do this with a resourcepack, icon backgrounds just need to be in a folder of `textures/gui/quest_backgrounds` and they will be auto added to the gui
