### ISSUE TITLE
[Feature Request]: increasing quest grid size

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [terrarium-earth/hercules#114]
### Is your feature request related to a problem?

running out of space making quests.

### Solution(s)

increase it to 5,000 units to each direction as a hard max. edit mode can freely pan through all the space. in view mode, it takes the furthest quests in each direction, adds 300-500 units out further from it and caps it there so players dont get lost. i say its okay due to clicking out and into the group causes you to be centered automatically anyway

### Mod Version

1.0.5

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
Already done in dev
