### ISSUE TITLE
[Feature Request]: quest desc scroll bar

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [terrarium-earth/hercules#116]
### Is your feature request related to a problem?

cannot see if there is more text

### Solution(s)

some indication that there is more to scroll down to would be neat, cause most people wouldn't think to scroll down to see more if it looks like it's the end

### Mod Version

1.0.5

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Additional context

example: https://imgur.com/a/a59y9mK

**Comment by ThatGravyBoat** [comment]
This should be requested on the hermes repo as it handles the question description
https://github.com/terrarium-earth/Hermes/issues

**Comment by ThatGravyBoat** [comment]
There I moved the request to hermes
