### ISSUE TITLE
[Bug]: Links occasionally don't appear until a refresh

### ISSUE THREAD

**Issue by lumiscosity** [terrarium-earth/hercules#12]
### Bug Description

Sometimes, when a link is made, it won't appear until you switch the group, reopen the menu or toggle edit mode.

### How to Reproduce?

1. Make a link between two quests.
2. Occasionally, the link will not appear.
3. Refresh the menu. The link will now appear.

### Expected Behavior

The link should always appear.

### Version

0.0.0

### Mod Loader Version

1.20, 0.14.21

### Mod Loader

Fabric

### Logs or additional context

Considering the "refreshing fixes it" nature of the bug, it could be related to #10

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
I couldn't get this to be reproduced so it may have been fixed by #10 so just let me know if you can get it to happen when the update gets released

**Comment by lumiscosity** [comment]
indeed, it's fixed!
