### ISSUE TITLE
[Bug]: Recipe Task completes upon Recipe Unlock rather than Crafting of Item

### ISSUE THREAD

**Issue by chronosacaria** [terrarium-earth/hercules#120]
### Bug Description

When using the `Recipe` Task to complete a task upon crafting an item, the current implementation is triggering upon the unlocking of _how_ to craft a recipe (see vanilla toast implementation) rather than upon the required item being crafted. This appears to be due to [hooking in to `ServerPlayerEntity#triggerRecipeCrafted`](https://github.com/terrarium-earth/Heracles/blob/05a40ea6508e28401490298bd9f7612770ceb609/common/src/main/java/earth/terrarium/heracles/mixins/common/ServerPlayerMixin.java#L39) rather than `Item#onCraftedBy`.  Given the current nomenclature that is used, the `Recipe` Task was understood to trigger upon crafting an item via its recipe. Whilst this might be a misunderstanding on our part, it is my suggestion that either the nomenclature be changed to be more clear or the mixin targeted method be changed to the aforementioned suggestion.

### How to Reproduce?

1. Create a Recipe Task Quest
2. Gather the ingredients needed to craft the item in the task
3. Gain completed task without crafting the item

### Expected Behavior

The task should trigger when the item is crafted via its recipe, rather than when the requisite ingredients are gathered.

### Version

1.0.5

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
I just fixed this it was using the recipe unlock method instead of trigger crafted, trigger crafted is correct see https://github.com/terrarium-earth/Heracles/commit/3160cb3e5c30872820964f061b10423d4a62f10a
