### ISSUE TITLE
[Feature Request]: An option to display Overview, Tasks and Rewards all on one screen

### ISSUE THREAD

**Issue by KonSola5** [terrarium-earth/hercules#126]
### Is your feature request related to a problem?

Currently, a simple checkmark quest requires THREE separate tabs: one for description, one for tasks, and one for rewards.

This system is cool for quests with long explainations, however not so when it comes to short quests.

![2023-11-02_18 38 10](https://github.com/terrarium-earth/Heracles/assets/125081901/667180f1-f5e2-4def-bc13-fc8014730619)
![2023-11-02_18 38 13](https://github.com/terrarium-earth/Heracles/assets/125081901/221c2b9f-3abd-40dc-aa66-61955f2203ca)
![2023-11-02_18 38 14](https://github.com/terrarium-earth/Heracles/assets/125081901/bccb0dbf-2c4e-417e-a168-81a38c580a9b)

### Solution(s)

An option to display Overview, Tasks and Rewards all on one screen.
(Mockup below.)
![obraz](https://github.com/terrarium-earth/Heracles/assets/125081901/820eef06-b66a-4339-9139-4281a3f3060d)

### Mod Version

1.0.5

### Mod Loader Version

1.20.1 - 0.14.23

### Mod Loader

Fabric

### Additional context

Other quest mods like FTB Quests, Better Questing and Hardcore Questing Mode do display everything on one screen, however they lack the ability to display descriptions, tasks and rewards separately.

**Comment by ThatGravyBoat** [comment]
You can already do this by using a task and reward element in the description like such
```html
<task quest="quest_id" task="task_id"/>
<reward quest="quest_id" task="reward_id"/>
```

**Comment by KonSola5** [comment]
Hmm, the mod would seriously benefit from some wiki/documentation.

**Comment by AdamRaichu** [comment]
> Hmm, the mod would seriously benefit from some wiki/documentation.

Agreed! I just discovered this mod, but I have no idea how to use it because there is no documentation, and searching for `earth.terrarium.heracles` on GitHub yielded no helpful results. Even the code from the example screenshot would be great!

**Comment by ThatGravyBoat** [comment]
Due to how new the mod is things update often so documentation would be out of date and I do not have time to keep updating it so for now there wont be indepth documentation heres an example for a few of the description options, but everything else is GUI based just press U and be an op then click edit in the top right and the UI should explain everything from there.

Example page
```html
<h1 color="#FF0000">Hello World!</h1>
<details summary="This is a details tag">
    <p>Crafting Recipe Spoiler!</p>
    <details summary="Sub Details">
        <p>Crafting Recipe Spoiler!</p>
        <details summary="Details Details">
            <p>Crafting Recipe Spoiler!</p>
        </details>
    </details>
</details>
<carousel height="32">
    <carousel-item>
        <img width="16" height="16" src="minecraft:textures/gui/advancements/backgrounds/adventure.png" />
        <p centered="true" shadowed="true">captions and stuff</p>
    </carousel-item>
    <carousel-item>
        <img width="16" height="16" src="minecraft:textures/gui/advancements/backgrounds/end.png" />
        <p centered="true">End Caption</p>
    </carousel-item>
</carousel>
<p>test</p>
<ol>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
</ol>
<hr>
</hr>
<columns>
    <column>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nulla nibh, scelerisque nec eros vel, venenatis
            venenatis eros. Proin convallis, erat sed efficitur malesuada, urna dolor suscipit lectus, mollis egestas
            felis augue in ex.</p>
    </column>
    <column>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nulla nibh, scelerisque nec eros vel, venenatis
            venenatis eros. Proin convallis, erat sed efficitur malesuada, urna dolor suscipit lectus, mollis egestas
            felis augue in ex.</p>
    </column>
</columns>
```
