### ISSUE TITLE
[Bug]: Removing any dependency on a quest with more than one crashes the game

### ISSUE THREAD

**Issue by lumiscosity** [terrarium-earth/hercules#13]
### Bug Description

Removing any dependency on a quest with more than one crashes the game, so long as that dependency is not the first or only dependency.

### How to Reproduce?

1. Create three quests.
2. Link quests first 2 then 3 to quest 1 with the link tool.
3. If you remove the dependency of quest 2 first, you can remove the dependency of quest 3 without a crash.
4. If you remove the dependency of quest 3 first, the game crashes.

### Expected Behavior

Dependencies can be safely removed in any order.

### Version

0.0.0

### Mod Loader Version

1.20, 0.14.21

### Mod Loader

Fabric

### Logs or additional context

Case 1: first 2, then 3
https://github.com/terrarium-earth/Heracles/assets/26834471/0e1e63ff-d47a-4cce-baa9-72d28791dc8c

Case 2: first 3
https://github.com/terrarium-earth/Heracles/assets/26834471/d36c42b5-9410-4910-b199-8629b24ec342

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Please provide the crash log file
