### ISSUE TITLE
[Feature Request]: Replace the remaining outline/fills with 9slice textures

### ISSUE THREAD

**Issue by sisby-folk** [terrarium-earth/hercules#134]
### Is your feature request related to a problem?

In order to make heracles fully themeable, many more elements currently rendered using fills and outlines need to be swapped to textures.

### Solution(s)

Here's our list of easily texturable bits, before we start giving it all a go.

Definitely not exhaustive, but (to us at least) the most obvious and accessible.

---

Widget (Task/Reward) backgrounds and separators:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/faa6d08c-8f07-4bd3-9928-26a2842a1cf4)

Two nineslices, one for the full box, one for the "box" that's from the left side to the icon separator. 

This allows similar theming to the sidebar, but is compatible with the current look.

Might need a third slice for an iconless version if that's used anywhere (bordering would be too hard otherwise)

---

Task/Reward List Headers:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/7910d8ff-72c4-4b4d-b737-a83d6994ba0b)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/f1b35984-65ec-44a7-8eca-02231f8bc9b9)

One nineslice for the full box.

---

Quest Summary Background:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/2cdf1156-4b78-4b2e-8f0e-5e63feb8cc3d)

5 nineslices, one for each quest state.

---

Task/Reward status headers:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/05741c3f-7472-43f4-be7c-feed15ff4fc1)

Three nineslices for the "tab" (dependency+locked/available+in-progress/complete+claimed), three matching for the border-like area.

---

Task Widget Progress Bar:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/68cfd041-7702-41ea-ae9b-cc215b7cea81)

Two nineslices (empty/full), possibly a third "completely full" slice.

---

Action buttons:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/ad31bae1-45e9-474d-882c-2d80645d7a06)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/aa4e44a1-0686-4fe0-bf99-606a95129463)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/59917016-5492-4641-8a2d-b538736c7dcb)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/73d35435-525d-4bfd-bde6-a18056c337f5)

All buttons that do something immediate when you click them. Might be worth splitting out the square ones.

3 nineslices: active, inactive, hovered.

---

Modal Button:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/4ac6c24d-1be1-4c55-b761-a3a0b6d9596c)

Buttons you click to open a modal.

3 nineslices: active, inactive, hovered.

---

Cycle Buttons:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/38dbd82b-3218-40e1-a3d8-97c2aaa0651b)

Buttons you click to cycle between available options.

3 nineslices: active, inactive, hovered.

---

Add Task/Reward button (AddDisplayWidget):

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/f06c5e1b-6c9c-4def-94b9-710eecd89eb8)

Two nineslices (normal/hovered), Two centre-blits (normal/hovered).

### Mod Version

1.0.5

### Mod Loader Version

0.20.2

**Comment by ThatGravyBoat** [comment]
modal buttons can wait as vanilla changed them to nine slice themselves in 1.20.2

**Comment by ThatGravyBoat** [comment]
just vanilla looking buttons in general can wait, no need to double work that will be replaced by mojang in the next update
