### ISSUE TITLE
[Bug]: Tasks in locked quests do not progress

### ISSUE THREAD

**Issue by sisby-folk** [terrarium-earth/hercules#148]
### Bug Description

When a quest is locked, its tasks don't track progress - this means that exploration quests will stay incomplete if their dependency isn't completed first, even if you've already visited that dimension/biome structure.

It also means that item quests for items you already have wont complete, requiring you to drop them and pick them back up.

### Expected Behavior

Tasks should track their own progress while the quest is locked. Ideally, this is done via a default-on setting for quests, so that quests like "kill 10 creepers" can still require the player to kill exactly 10 after sighting the task as being unlocked.

### Version

1.1.6

### Mod Loader Version

0.20.2

### Logs or additional context

There are still technical limitations with the suggested solution. For a "do not progress while locked" quest, item tasks are still not updated when the quest is unlocked, leading to the "drop and pick up" problem. Ideally, item tasks should be able to be forced to check the whole inventory, which can be triggered whenever a quest becomes unlocked.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by sisby-folk** [comment]
@ThatGravyBoat I saw this got fixed for stat and advancement tasks, do you still need to drop and re-pick up items when acquire item tasks unlock that you already have the items for?

**Comment by bluebear94** [comment]
For a setting to allow progressing in locked quests, which would still be useful for some situations, I’m working on a PR: #270
