### ISSUE TITLE
[Bug]: Trying to load client classes on the server

### ISSUE THREAD

**Issue by sleepy-evelyn** [terrarium-earth/hercules#150]
### Bug Description

Mod loads fine on the client but not for a dedicated server. It's trying to load client classes.

### Version

1.1.6

### Mod Loader Version

1.20.1 - Quilt 0.22.0-beta1

### Mod Loader

Quilt

### Logs or additional context

https://gist.github.com/sleepy-evelyn/508b9a96c651c043165ef2bd1c901545

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Update Resourceful Lib
