### ISSUE TITLE
[Feature Request]: click on item task to view recipe in recipe viewer (emi/rei/jei)

### ISSUE THREAD

**Issue by Abbie5** [terrarium-earth/hercules#155]
### Mod Version

1.1.7

### Mod Loader Version

fabric loader 0.14.25, fabric api 0.91.0+1.20.1

**Comment by ThatGravyBoat** [comment]
Implemented

**Comment by sisby-folk** [comment]
Can we get this reopened for EMI explicitly?

[FTB-Mods-Issues#312](https://github.com/FTBTeam/FTB-Mods-Issues/issues/312) is actually the reason we contributed to Heracles in the first place, and we'd be remissed if we didn't track whether Heracles can beat FTB's 1.5+ year turnaround time :P
