### ISSUE TITLE
[Feature Request]: Undo/redo

### ISSUE THREAD

**Issue by Cyntheon** [terrarium-earth/hercules#161]
### Is your feature request related to a problem?

It would be nice to be able to undo/redo while editing a quest, especially in the Overview section.

### Solution(s)
- (General) Ctrl+Z/Y for Undo/Redo
- (Overview) Undo/Redo buttons to the left of the Bold/Italic/Underline/etc. buttons

### Mod Version

1.1.7

### Mod Loader Version

1.20.1 - 47.2.19

### Mod Loader

Forge

**Comment by SubordinalBlue** [comment]
I'll second that; when having the full description selected (for example, in preparation to 'cut') a single wrong key press loses everything.

I imagine an `undo` would also be handy when one is not sure what they did get into a state where the description renders as a blank screen (though one does get better at dealing that situation).
