### ISSUE TITLE
[Feature Request]: Group Refactor: Itemstack icons

### ISSUE THREAD

**Issue by CodexAdrian** [terrarium-earth/hercules#163]
### Is your feature request related to a problem?

groups not pretty enough, need more icon plz

### Solution(s)

Add the option to add an item stack as a group's icon

### Describe alternatives you've considered

ending you

### Mod Version

n/a

### Mod Loader Version

n/a

### Mod Loader

N/A

**Comment by ThatGravyBoat** [comment]
Already exists

**Comment by CodexAdrian** [comment]
*You coulda said that before i made the issue bro*
