### ISSUE TITLE
[Feature Request]: "Snap-to-Grid" Mode

### ISSUE THREAD

**Issue by CodexAdrian** [terrarium-earth/hercules#164]
### Is your feature request related to a problem?

Aligning quests to look right can be frustrating without a visible grid and with such a small unit for positioning quests

### Solution(s)

Add a mode to toggle between bigger sized grid squares when moving around quest.

### Describe alternatives you've considered

crying

### Mod Version

n/a

### Mod Loader Version

n/a

### Mod Loader

N/A

**Comment by SubordinalBlue** [comment]
Awesome sauce idea.

Perhaps snap on some useful sub-division, like 8 or 16?
Some quests icon sets (the default, Sisby’s great Paper&Ribbon theme) use smaller icons, others (AoF7’s) use larger ones.

(don’t hold me to those numbers; I’m without pc rn)

**Comment by SubordinalBlue** [comment]
Perhaps even an alternate grid shape or two?

I know I and NitroFenix have at times wanted to lay out quests according to a hex grid pattern.

**Comment by ThatGravyBoat** [comment]
Done in dev
