### ISSUE TITLE
[Bug] Quests don't persist on servers

### ISSUE THREAD

**Issue by VELD-Dev** [terrarium-earth/hercules#166]
### Is your feature request related to a problem?

It's very frustrating that the quests replicate weirdly among a server. When everyone can create those quests on the server but when they leave or when the server shuts down, the quests just disappear.

### Solution(s)

I think it would be a good idea that, if the server provides a list of quests, then the client ones are *not* loaded or loaded in a different place, or separately, for example with a Server category (grouping groups) and a User category (grouping groups too), and that the server quests can only be made by OPs, meanwhile user quests cannot give themselves items.
Actually, it's tedious to have to handle very unconsistently the quests.

### Describe alternatives you've considered

Maybe there could also be players-shared quests ? In some context it would be an interesting feature.

### Mod Version

1.1.7

### Mod Loader Version

1.20.1-47.1.84

### Mod Loader

NeoForge

### Additional context

I made a modpack and I packed some quests with it, then I wanted to update the quests afterwise on the server but I remarked that when I created those, none was saved, neither on client nor on server. And people can overwrite quests, without even needing permissions.

**Comment by CodexAdrian** [comment]
I've converted this to a bug, we don't plan on adding your solution, but we will fix the issue with the quests not saving properly on servers.

Could you provide more context about your server?

**Comment by VELD-Dev** [comment]
The server is running on Neoforge 1.20.1, under Heracles 1.1.7.
I did some modifications from my client on the server, and when I shut it down, only the ones I made on the client remained on the server once rebooted. It's probably a bug, but it's a little bit confusing to have no documentation about that, it's maybe my bad though.

**Comment by CodexAdrian** [comment]
You made modifications to the quest book while you were on a server, you restarted the server, and the server saved the changes you made but the changes werent reflected when you went into a singleplayer world?

If thats the case, this is the intended behavior.

**Comment by CodexAdrian** [comment]
When you're dealing with things like datapacks and the like, the 'server' is what determines what you get, in terms of recipes, tags, and in this case, quests. When you're on a server, the server is what has that information and sends it to the client. When you're in single player, the client acts as its own server. When you go and edit that information, it goes and edits it on whatever is currently acting as the server. This is just how server sided information works in minecraft, its not expected behavior for edits to impact both the client that was making the changes and the server that received them.

**Comment by VELD-Dev** [comment]
> You made modifications to the quest book while you were on a server, you restarted the server, and the server saved the changes you made but the changes werent reflected when you went into a singleplayer world?
> 
> If thats the case, this is the intended behavior.

No no, the changes didn't persist on server *after* the reboot
