### ISSUE TITLE
[Bug]: 1.20.1 Crash when click edit quest button

### ISSUE THREAD

**Issue by Proxwian** [terrarium-earth/hercules#167]
### Bug Description

[crash-2024-01-21_21.13.18-client.txt](https://github.com/terrarium-earth/Heracles/files/14002315/crash-2024-01-21_21.13.18-client.txt)

### How to Reproduce?

1. Open quests window
2. Enable edit mode
3. Select default quest
4. Click on Edit button
5. Game crashed

### Version

1.1.7

### Mod Loader Version

1.20.1 - 47.2.19

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
This is an issue with visual improvements, you can find the issue report on their repo for it https://github.com/TeamMidnightDust/VisualOverhaul/issues/59
