### ISSUE TITLE
[Bug]: Adding task from another quest to overview bugs overview renderer

### ISSUE THREAD

**Issue by Auseawesome** [terrarium-earth/hercules#169]
### Bug Description

If you add a task from another quest for example: <task task="knife" quest="get_knife"/> and "get_knife" isn't the current quest. The overview no longer renders, using this exact same line works fine in the quest "get_knife"

### How to Reproduce?

1. Create 2 quests
2. Add a task to one of the quests
3. Add <task task="TASKID" quest="QUESTID"/> to the other quest
4. Rendering bugs on the overview

### Expected Behavior

When adding a task from another quest, it shows the steps required for the task and has a button to jump to the other quest

### Version

1.1.8 Dev Build (Built at 19:20 27/01/24)

### Mod Loader Version

47.1.96

### Mod Loader

NeoForge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [x] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Yeah this was never meant to be possible due to how data is loaded or else id need to load the entire quest list on the client which is massive. In new versions it has been fixed
