### ISSUE TITLE
[Bug]: "submit item" non-functional

### ISSUE THREAD

**Issue by grahamfoxrollup** [terrarium-earth/hercules#172]
### Bug Description

can't submit items or claim rewards if items say 100%

### How to Reproduce?

create tasks to submit items
create reward for items
change tasks for item submission.
try to submit items and try to claim rewards

### Expected Behavior

submitted items are removed from inventory before marked green and 100%
when all tasks completed and "1 reward left" claim rewards button is clickable.

### Version

1.1.9

### Mod Loader Version

1.20.1 - 47.2.18

### Mod Loader

Forge

### Logs or additional context

video of bug
https://github.com/terrarium-earth/Heracles/assets/138266442/16e05bae-9d1d-43f1-93d3-575265fcd47d

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
This is really only an issue with editing quests. You should use the `/heracles reset` to reset progress and fix this issues for your players.
