### ISSUE TITLE
[Bug]: how am I supposed to depend on this or any of your mods

### ISSUE THREAD

**Issue by walksanatora** [terrarium-earth/hercules#173]
### Bug Description

when I go to your maven (which is apperently at https://maven.teamresourceful.com/ I could not find this linked anywhere)
I am unnable to search for *any* packages

### How to Reproduce?

1. go to your (hard to find) maven repo page https://maven.teamresourceful.com/
2. try to search packages without logging in (since we cant)
3. realize you cant
4. give up and use FTB

### Expected Behavior

the ability to search packages on your maven and being able to actually find the maven

### Version

?.?.?

### Mod Loader Version

????

### Mod Loader

N/A

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
You can ask sonatype the maven provider to not leak IPs if you want to search (https://github.com/sonatype/nexus-public/issues/266), you also are using the wrong repo url `https://maven.teamresourceful.com/repository/maven-public/`

And dont be so rude for no reason, being rude is not going to get you anywhere in life.

**Comment by walksanatora** [comment]
still cant browse the maven for any jars. why leave it up if you are not going to use it
you could just turn it into a WebDAV like blamejared maven. or use Reposilite like ladysnake maven

**Comment by ThatGravyBoat** [comment]
wdym? we do use it? 100s of mods use it, just because something isnt publicly visible doesnt mean the endpoints dont exist.

**Comment by ThatGravyBoat** [comment]
also not that easy to just switch mavens, our maven has over 150k thousand files on it

**Comment by walksanatora** [comment]
you make it needlessly complicated to locate your mods.
even something as a simple
```
to depend on this mod add X to your dependecies block and Y to your dependicies block
```

**Comment by walksanatora** [comment]
because as it stands it seems like you dont want people touching your maven in any way

**Comment by ThatGravyBoat** [comment]
I added dependency info the read me for this, you dont need any other mavens due to us hosting and mirror all required dependencies needed

**Comment by ThatGravyBoat** [comment]
gradle transitive dependencies will handle the rest
