### ISSUE TITLE
[Feature Request]: Reveal task or reward title via hover text when in edit mode

### ISSUE THREAD

**Issue by SubordinalBlue** [terrarium-earth/hercules#176]

**Comment by ThatGravyBoat** [comment]
what exactly do you mean by this?

**Comment by SubordinalBlue** [comment]
Some of the people that have been contributing to AoF7’s quests have expressed a desire see what they named a task or reward after having made it, without tabbing out to read the json file.

(I’m fine with the later, but it’s my habit to have MC in a not-very-big window when doing quest work)

Having it show as hover text, only when in edit mode, is just my idea for solving it. Doesn’t really have to be done that way.

**Comment by ThatGravyBoat** [comment]
oh ive done this in my UI refactor, ive also added a way to copy the id, along with dedicated buttons to inserting a reward/task html entry into the description with a UI for selecting the reward/task I think all 3 of these should solve all the hard points with them, if they dont is there anything else I can do?

**Comment by SubordinalBlue** [comment]
Sounds very good; a much more complete solution!

**Comment by ThatGravyBoat** [comment]
okay ill close this then
