### ISSUE TITLE
[Feature Request]: Allow selecting and moving multiple quests at once

### ISSUE THREAD

**Issue by elaniquilador01** [terrarium-earth/hercules#178]
### Is your feature request related to a problem?

It's annoying having to move multiple quests one by one when you want to add new ones and make it look good

### Solution(s)

Allow selecting multiple quests at once and dragging them in the same direction all at once 

### Mod Version

Current

### Mod Loader Version

Current

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
Duplicate of #38
