### ISSUE TITLE
[Feature Request]: Add velocity support

### ISSUE THREAD

**Issue by windy664** [terrarium-earth/hercules#179]
### Is your feature request related to a problem?

When using veocity proxy server , 

heracles_quest_progress.dat cannot be synchronized between two servers

### Solution(s)

To add  velocity support

or add mysql to save this progress

### Mod Version

1.1.9

### Mod Loader Version

1.20.1-Fabric-0.15.6

### Mod Loader

Fabric

**Comment by CodexAdrian** [comment]
This is out of scope for this mod
