### ISSUE TITLE
[Feature Request]: Ability to hide quests when dependencies are hidden

### ISSUE THREAD

**Issue by Auseawesome** [terrarium-earth/hercules#181]
### Is your feature request related to a problem?

I can't set a whole line of quests to be revealed when a quest is completed

### Solution(s)

Add a 'hidden until: dependency revealed' option

### Describe alternatives you've considered

Add a way to keep hidden until a command is run or scoreboard is updated so this can be done manually.

### Mod Version

1.1.9

### Mod Loader Version

47.1.96

### Mod Loader

NeoForge

### Additional context

Need to hide other quests to avoid confusing new players on where to start, or why quests aren't unlocking

**Comment by SubordinalBlue** [comment]
That sounds suspiciously like what setting `Hidden Until` to "in progress" does. Have you tried that?

For example, setting that on the rounded triangle check mark quest in this shot keeps it and it's small cluster of dependents all hidden until the task in _it's_ dependency (the pink shaded heptagon in the screen shot) is completed. Note, in this shot the dependency arrow of the rounded-triangle task is set to be hidden.

<img width="190" alt="image" src="https://github.com/terrarium-earth/Heracles/assets/6677700/ef43b17c-9470-4f4c-aa89-e0b659d25c62">


<img width="720" alt="image" src="https://github.com/terrarium-earth/Heracles/assets/6677700/5c3d8f72-0aa3-4f82-8e73-a9276a19ee9e">

**Comment by Auseawesome** [comment]
No, in progress hides until the dependency directly before is completed. I need one that unhides when the dependency before it unhides allowing me to chain a bunch of dependencies unhiding from one quest being completed
