### ISSUE TITLE
[Feature Request]: Syntax Error Reporting

### ISSUE THREAD

**Issue by Auseawesome** [terrarium-earth/hercules#183]
### Is your feature request related to a problem?

Currently, if some syntax error is made such as forgetting the / before the >, all quest rendering bugs and goes blank.

### Solution(s)

Adding some text that attempts to explain the error, or just says where it occurs would be more than useful.

### Describe alternatives you've considered

Forcing quests to attempt to render even with issues, adding more failsafes for rendering

### Mod Version

1.1.9

### Mod Loader Version

47.1.96

### Mod Loader

NeoForge

**Comment by ThatGravyBoat** [comment]
Fixed in dev

**Comment by Auseawesome** [comment]
Great, thanks

**Comment by Auseawesome** [comment]
Mind telling me where I can find this to build it? I can't find a commit pertaining to this issue

**Comment by ThatGravyBoat** [comment]
It is part of the UI rewrite which is not public yet

**Comment by Auseawesome** [comment]
K, I'll be waiting for that to release, do ping me on discord or reply here when I can access this change!
