### ISSUE TITLE
[Feature Request]: Viewing task/reward IDs without external editor

### ISSUE THREAD

**Issue by Auseawesome** [terrarium-earth/hercules#184]
### Is your feature request related to a problem?

When adding task/reward widgets, unable to easily check ID of them to put into the task widget.

### Solution(s)

When editing the task/reward, like in the edit menu for quests add the task/reward ID at the top of the window.

### Describe alternatives you've considered

Add a button to copy task ID or to copy a widget to clipboard.

### Mod Version

1.1.9

### Mod Loader Version

47.1.96

### Mod Loader

NeoForge

**Comment by ThatGravyBoat** [comment]
In UI Refactor dev
