### ISSUE TITLE
[Bug]: `/heracles reset` command does not work with the otherwise permitted range of quest names

### ISSUE THREAD

**Issue by SubordinalBlue** [terrarium-earth/hercules#187]
### Bug Description

Quest names with spaces, and other punctuation, will show in auto-complete, but the actual command won't parse.

<img width="321" alt="image" src="https://github.com/terrarium-earth/Heracles/assets/6677700/aeefdf78-8b46-401e-8aab-ab58550e1d21">

### Version

1.1.9

**Comment by ThatGravyBoat** [comment]
Fixed
