### ISSUE TITLE
[Feature Request]: Grid placement mode for quests

### ISSUE THREAD

**Issue by lumiscosity** [terrarium-earth/hercules#19]
### Is your feature request related to a problem?

Precisely moving quests can be quite time consuming, so a toggleable grid snap system could help assist with the process.

### Solution(s)

A new button should be added to the edit mode that enables a grid - perhaps also opening a dropdown specifying the grid size. When moving quests with the grid enabled, they should snap to the grid position.

### Describe alternatives you've considered

Not quite an alternative solution, but some sort of system for nudging quests with key presses would be welcome.

### Mod Version

0.0.2

### Mod Loader Version

1.20, 0.14.21

### Mod Loader

Fabric

**Comment by wanesty** [comment]
https://github.com/terrarium-earth/Heracles/issues/5#issuecomment-1586079282 was discussed here :)
