### ISSUE TITLE
[Feature Suggestion]: Optional larger sizes for quest icons (per quest)

### ISSUE THREAD

**Issue by SubordinalBlue** [terrarium-earth/hercules#190]
I've seen this in more than one pack. On AoF6 it was used sparingly and effectively, imho, for the final quest of each chapter/group where one would get a trophers reward.

Here's an example for the _Spirit_ mod from then:

![image](https://github.com/terrarium-earth/Heracles/assets/6677700/8a77baee-44f2-4cd2-9801-f51715c194a5)

(actually surprised I this hasn't been suggested already; apologies if it has and I missed it when checking.)

**Comment by ThatGravyBoat** [comment]
This can already be done with the current system as you can change the width and height of the backgrounds in an mcmeta file, see the diamond and hexagon backgrounds in the base mod for how to do those.

**Comment by SubordinalBlue** [comment]
A misunderstanding perhaps?

Suggestion is to optionally present particular quests' icons scaled up—both the background shape and the item inside it.
