### ISSUE TITLE
[Feature Request]: Heracles Individual Task Rewards/Dependencies

### ISSUE THREAD

**Issue by Xxcaden9999xX** [terrarium-earth/hercules#191]
### Solution(s)

For example, I could make a quest for discovering and exploring the illager hideout in the dungeons and taverns datapack. I could make it so that When you find the map to the structure, it would run a command to place a waypoint on the nearest hideout, once you've completed the structure task of finding the hideout, the reward would be to delete the waypoint, and unlock the next task(s)

### Mod Version

1.1.10

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
We will not be adding dependencies to individual tasks and rewards as this just adds an extra step of complexity for something that can already be achieved by using another quest
