### ISSUE TITLE
[Feature Request]: More Controllable Variables/More Specific Syntax

### ISSUE THREAD

**Issue by Xxcaden9999xX** [terrarium-earth/hercules#192]
### Is your feature request related to a problem?

Lets say we have a task where we need to free an allay in an illager hideout from Dungeons N Taverns. I would probably use a button, or breaking a certain fence to trigger the task
however I run into the same issue where it can be any ol button or fence.

### Solution(s)

A solution would to add more specific controllable variables/functions I could use, such as checking if the player is in the right Structure/Part of a Structure when Opening that chest or pressing that button. 

An example would be 

    "LootChests": {
      "icon": {
        "item": {
          "id": "minecraft:chest",
          "count": 1
        },
        "type": "heracles:item"
      },
      "block": "minecraft:chest",
      "title": "Loot the Treasure Chests",
      "type": "heracles:block_interaction",
      "structures": "minecraft:desert_pyramid" <<here
    }

### Describe alternatives you've considered

I could use NBT tags to specify what specific entity/block im supposed to interact with, but that would require me to modify the structure mod itself, and replace each block/entity with a NBT marked one, but that would be extremely tedious.

### Mod Version

1.1.10

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
This is way to fine grained for Heracles, this complexity will become unmaintainable, I suggest if you want this such fine grained control to use a dummy quest and something like kubejs as it was made for this.
