### ISSUE TITLE
[Feature Request]: New Ways to Unlock Quests.

### ISSUE THREAD

**Issue by Xxcaden9999xX** [terrarium-earth/hercules#193]
### Solution(s)

It would be really useful if there were more specific ways you could unlock a quest, such as talking to an NPC. Like if were to set a stat type task where I talked to an NPC, and a Accept or Decline from the NPC would output a different stat, accept being the one that unlocks the quest.

### Mod Version

1.1.10

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
We don't plan on adding such a feature to the base mod as we 1 don't have NPCs and 2 most NPC mods allow the execution of commands which you can use the dummy task for which was made for this
