### ISSUE TITLE
[Feature Request]: Select Tool have `Left Click` -> open quest; `Right Click` -> open quest details panel

### ISSUE THREAD

**Issue by SubordinalBlue** [terrarium-earth/hercules#194]
Spreading actions across buttons first, before using the single-vs-double click distinction, seems preferable in general.

  Also, double click in game--just sometimes--will register as a short drag and then a click, thus moving the quest a bit before opening it.

  In the current UI this would avoid a bit of back-and-forth mousing and tool switching when one is in edit mode and wants to open a quest that is currently positioned to be covered by the quest details panel. Since #188 is already in the coming UI Refactor, this will become less annoying, but is still welcome because the detail panel opens before the second click registers.

**Comment by ThatGravyBoat** [comment]
the panel will be removed in the UI update and most of it will be added in a context menu so kind of like what you requested

**Comment by SubordinalBlue** [comment]
Doesn't address the mc(?)-sometimes-registers-double-click-as-drag-then-click issue though.

Good to hear the detail-panel-occluding-some-quests issue is going away!
