### ISSUE TITLE
[Bug]: Toggling the edit mode briefly moves the cursor to the center of the screen

### ISSUE THREAD

**Issue by lumiscosity** [terrarium-earth/hercules#20]
### Bug Description

See title. Might not be noticeable on lower refresh rate devices - I'm using a 144hz monitor.

### How to Reproduce?

1. Keep clicking the "Toggle Edit Mode" button.

### Expected Behavior

The mouse cursor stays in the right place the whole time.

### Version

0.0.2

### Mod Loader Version

1.20, 0.14.21

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by lumiscosity** [comment]
This issue also seems to happen when switching groups.

**Comment by ThatGravyBoat** [comment]
This is actually a vanilla "bug" that I fix by just moving your mouse back to the original position I cant really do much about it.
