### ISSUE TITLE
[Bug]: Crash when creating Block Interaction

### ISSUE THREAD

**Issue by FooterManDev** [terrarium-earth/hercules#200]
### Bug Description

When creating a task for block interaction, I get a crash when using a Crafting Table as the block to interact with.

### How to Reproduce?

Create a Quest,
Create a Block Interaction task, make it require interacting with a Crafting Table,
Should crash right after selecting the table.

### Expected Behavior

No crash.

### Version

1.1.10

### Mod Loader Version

1.20.1 - 47.2.20

### Mod Loader

Forge

### Logs or additional context

https://mclo.gs/q8lfmZ1 - Crash Log
https://mclo.gs/SVJ4w7b - Latest Log

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Fixed in https://github.com/terrarium-earth/Heracles/commit/b70d2125d80b8582c8ea4161b77a53a48a7b4101 will come in the next update
