### ISSUE TITLE
[Bug]: Crash when creating a Structure task

### ISSUE THREAD

**Issue by euquinox** [terrarium-earth/hercules#202]
### Bug Description

The client crashed as soon as I started searching for a name of a structure in the search bar
Specifically, minecraft:nether_fortress 

### How to Reproduce?

1. Create a task
2. Start typing in the Structure search bar

### Version

1.1.11

### Mod Loader Version

1.20.1 - 47.2.20

### Mod Loader

Forge

### Logs or additional context

[heraclescrash.txt](https://github.com/terrarium-earth/Heracles/files/14549657/heraclescrash.txt)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Fixed in dev, and minecraft:nether_fortress isnt a structure
