### ISSUE TITLE
[Bug]:  Carousel buttons broken when Carousel is inside a Column

### ISSUE THREAD

**Issue by SubordinalBlue** [terrarium-earth/hercules#203]
### Bug Description

It renders _perfectly_, and I'd really like to use it that way for same layouts.

But the buttons to switch carousel-item become non-functioning. They will still high-light on hover, but don't react to clicks.

**Comment by ThatGravyBoat** [comment]
Can you please put this on the Hermes' repo

**Comment by SubordinalBlue** [comment]
literally just woke up and had the thought "wtf did I put that (this) on the Heracles repo?"

Refiling...
