### ISSUE TITLE
[Feature Request]: Receive Quest book on spawn

### ISSUE THREAD

**Issue by NitrolessWasTaken** [terrarium-earth/hercules#205]
### Is your feature request related to a problem?

The quest interface is only accessible via keybind in survival mode with no other mods installed

### Solution(s)

The quest book should be given to the player on spawn (configurable)

### Describe alternatives you've considered

This is possible by installing other mods, but I don't think that should be the case
Alternatively the quest book could have a crafting recipe or there could be a button somewhere in the player's inventory (similar to FTB Quests, or completely different)

### Mod Version

1.1.11

### Mod Loader Version

1.20.1 - 0.15.7

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
We have support for REI buttons, and as for an option to spawn with a book this is better handled by the pack developer themselves as many will already turn off the option and have their own spawning inventory things
