### ISSUE TITLE
[Suggestion]: Support Bedrock's expanded set of formatting code colors, for the editor gui bits

### ISSUE THREAD

**Issue by SubordinalBlue** [terrarium-earth/hercules#207]
Looks like Bedrock has 11 more colors to be had from formatting codes.
Why should they get all the fun?

(also, more colors accessible for those that haven't gone into writing html tags (and using color="" attributes)

https://minecraft.fandom.com/wiki/Formatting_codes

**Comment by ThatGravyBoat** [comment]
While I like the idea, implementing custom formatting codes is not really easy as we just let vanilla handle it and they hardcode it

**Comment by SubordinalBlue** [comment]
This is old now, but I wouldn't suggest doing it with actual custom formatting codes... just have Herecles' pre-parser insert the right <color> for Hermes to render it.
