### ISSUE TITLE
[Feature Request]: Random Rewards

### ISSUE THREAD

**Issue by seriousfreezing** [terrarium-earth/hercules#210]
### Is your feature request related to a problem?

I converted my quests to this mod, but it doesn't convert much. Because it doesn't have the feature, like: There's no way to do random looting as a reward in quests. 

### Describe alternatives you've considered

So far the only solution for me to convert my quest would be to just place one of the items, but it would make the experience more boring.

### Mod Version

1.1.11

### Mod Loader Version

1.20.1 - 0.15.7

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
You can use a loot table reward and convert your rewards to a loot table, loot tables are far more versatile and can be used with mods like loot bags for multiple purposes.

**Comment by seriousfreezing** [comment]
So why hasn't Odysseus already done this for me?

**Comment by ThatGravyBoat** [comment]
Odysseus converts only basics so far, loot tables would require out putting different files as to load a loot table you would need a mod like open loader, kubejs, or global packs to load the datapack with the loot tables.

**Comment by seriousfreezing** [comment]
Okay, but how do I get these loot rewards? No one tells me how
