### ISSUE TITLE
[Bug]: Can't connect to server (...YabnElement.isNull()... error)

### ISSUE THREAD

**Issue by WimpieRatte** [terrarium-earth/hercules#223]
### Bug Description

Minecraft 1.20.1

Just in case this is not a Heracles issue, I logged this matter with ResourcefulLib as well: https://github.com/Team-Resourceful/ResourcefulLib/issues/13

Error message:
![2024-05-13_19 47 07](https://github.com/terrarium-earth/Heracles/assets/42098550/02ffe03b-833f-45fa-bfa7-4ba9d47ed3cb)

People are unable to join after they were in the first time.

Log is attached.

One way I found that clears it, is if I stop the server, then delete the data/heracles* files in the world and then start the server.
But then the same thing happens all over again.

### How to Reproduce?

1.    Install "Colonies and Technologies" modpack
2.    Start a server version (the following mods will need to be excluded on the server side: Panorama Screens, Footprint Particle, Embeddium, watermedia, better beds reforged, BiomeParticleWeather, cherished worlds, clean tooltips, completionist index, current game music track, distinguished potions, effect descriptions, equipment compare, essential, forgematica, helditemtooltips, improved sign editing, loading backgrounds, mafglib, mob plaques, modpack update checker, no resourcepack warnings, overflowing bars, seamless, slot cycler, splashy, trade uses, traveler's titles, WI Zoom, yeetus experimentus)
3.    Join the server (first time should be fine)
4.    Complete some quests and exit
5.    Try to rejoin

### Expected Behavior

Be able to log into the server.

### Version

1.1.12

### Mod Loader Version

1.20.1 - 47.2.30

### Mod Loader

Forge

### Logs or additional context

[latest.log](https://github.com/terrarium-earth/Heracles/files/15299039/latest.log)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by SubordinalBlue** [comment]
Wow...line 5088 looks massive.

`5088-[13May2024 19:46:57.758] [Netty Client IO #1/ERROR] [earth.terrarium.heracles.Heracles/]: Failed to decode sync quests packet: <large YabnObject follows...>`

**Comment by WimpieRatte** [comment]
I'm currently trying to unload all quests and load them back one section at a time to try and pinpoint why this happens.
But it's a very slow grind, because I have over 200 files in my heracles config folder.

Also, this issue does not happen when inviting friends via the Essential mod to a single player world.
Only on dedicated servers.

**Comment by WimpieRatte** [comment]
Latest details from Discord chat:
SubordinalBlue — Today at 1:50 AM

> random idea... does your client already have the exact same quest files as the server?

wRatte — Today at 1:51 AM

> I tried that in the beginning and when I noticed that it takes the server's quest files, I stopped trying to update the client.
> When I had my "main" quests loaded on the server and only the welcome quest on the client, it worked.
> but then when I added the "main" quests back in the client - it errored again.

**Comment by ThatGravyBoat** [comment]
Looking at it, its because of a null yabnelement which is a valid yabn element this is an underlying issue with how I wrote yabnops to mimic jsonops in DFU <https://github.com/Mojang/DataFixerUpper/issues/62> ill have to figure out a workaround the issue seems to be that the nbt fields are not there so they default to null so a quick way would be to add empty object nbt fields

**Comment by ThatGravyBoat** [comment]
Fixed in latest resourcefullib version
