### ISSUE TITLE
[Feature Request]: Snap-to-grid feature in Heracles editor

### ISSUE THREAD

**Issue by tazzanmc** [terrarium-earth/hercules#230]
### Snap-to-grid feature in Heracles editor 

I want to make a nice, evenly spaced quest tree. This is possible in Heracles, but it's very tedious and required a lot of manually entering values or moving the mouse very very small distances.

### Solution(s)

Add a toggle to allow quest buttons to snap to a grid. This could be a variable grid that the user could edit, but that's not necessary, any grid would be good.

### Mod Version

1.1.12

### Mod Loader Version

1.20.1 47.2.21

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
done in UI refactor
