### ISSUE TITLE
[Feature Request]: "Go to Location/Coordinates" Quest Task

### ISSUE THREAD

**Issue by ToppyTopology** [terrarium-earth/hercules#233]
### Is your feature request related to a problem?

Adding a quest task that is completed when reaching a certain area specified with position coordinates and its size (similar to FTBQuests' Location task) can be helpful when making map specific quests. 

### Mod Version

1.1.13

### Mod Loader Version

1.20.1 - 47.2.32

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
This already exists just has to be done via the json, its type is heracles:location and takes a predicate field of this 
![image](https://github.com/terrarium-earth/Heracles/assets/26934102/22c6c29b-83e2-44f3-a571-f30097849436)
I suggest for autocomplete in json to use this: https://marketplace.visualstudio.com/items?itemName=FooterMan.heracles-support

**Comment by ToppyTopology** [comment]
> This already exists just has to be done via the json, its type is heracles:location and takes a predicate field of this ![image](https://private-user-images.githubusercontent.com/26934102/337944979-22c6c29b-83e2-44f3-a571-f30097849436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDUwOTUsIm5iZiI6MTcyNDI0NDc5NSwicGF0aCI6Ii8yNjkzNDEwMi8zMzc5NDQ5NzktMjJjNmMyOWItODNlMi00NGYzLWE1NzEtZjMwMDk3ODQ5NDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEyNTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYjlmMGNkMTY2ZDQ5NDY5ZDQxMTMxMTJhZTRjMTNkNWE1M2UwMzM1NDc0M2RhZWI5NjMxMzkyN2Y0YjQ5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DdC8xOrK4m2KC6lvvuReH51MotkYZ9Dw1kqdSreBuiQ) I suggest for autocomplete in json to use this: https://marketplace.visualstudio.com/items?itemName=FooterMan.heracles-support

hello, for some reason it still doesn't seem to appear in the task screen or do anything. It seems that reloading the quest file will just delete the task. Ive confirmed it should be correct since I used your ftb quest importing tool and does the same thing in the quest file
