### ISSUE TITLE
[Feature Request]:  For task items with NBT, allow for "equal to or greater" (or lesser) behavior

### ISSUE THREAD

**Issue by SubordinalBlue** [terrarium-earth/hercules#234]
### Is your feature request related to a problem?

Prompted to suggest this for our easier/basic TerraShatterer quest.

The hard quest is a simple matter... the NBT for that one specifies the maximum mana a TerraShatterer can have, it's easy for the player to hit that exact number.

For the easier/basic "Terra Tools" quest, a much lower, non-zero amount would be nice: they player the still has to charge the tool at least somewhat with mana... which is a key part of what makes the Terra Shatterer different than a regular pickaxe.

In FTBQ/AoF6, the quest would satisfy with any TerraShatter with a mana amount greater or equal to the amount specified in the quest file.

A similar behavior/ability for Heracles would be nice. I imagine more uses could be made of it than just this one quest I've used to illustrate the matter.

### Mod Version

latest

### Mod Loader Version

Fabric

**Comment by ThatGravyBoat** [comment]
While I like the idea this will be come obsolete instantly when we upgrade to 1.21 so I think this change would be too much effort for not much gain

**Comment by CodexAdrian** [comment]
In 1.21 mojang has added "ComponentPredicates" that will enable much more flexible component matching, we'll likely end up using it in heracles
