### ISSUE TITLE
[Bug]: Quests screen handled as an inventory by Inventory Profiles Next

### ISSUE THREAD

**Issue by lumiscosity** [terrarium-earth/hercules#29]
### Bug Description

The Inventory Profiles Next buttons appear on the quests menu overlapping the groups; they shouldn't appear at all, since the quests menu isn't an inventory.

### How to Reproduce?

Enable the quests menu with Inventory Profiles Next installed.

### Expected Behavior

The buttons do not appear.

### Version

0.0.2 of Heracles, 1.10.3 of Inventory Profiles Next

### Mod Loader Version

1.20, 0.14.21

### Logs or additional context

The readme of Inventory Profiles Next mentions how to tag a GUI as not an inventory (with an @IPNIgnore annotation).

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Interesting that the mod doesnt check if there are actually inventory slots, but ill be changing all the menus to just client side screens and manually sync all the stuff anyway because of this and #20 because menus also cause that bug
