### ISSUE TITLE
[Bug]: Ghost copies of quests in a group appear in all other groups

### ISSUE THREAD

**Issue by lumiscosity** [terrarium-earth/hercules#31]
### Bug Description

Ghost copies of quests in a group appear in all other groups at 0, 0. 

### How to Reproduce?

1. Create at least two groups and put a quest in each of them.
2. A copy of the quest from each group will appear at 0, 0 in the other group.

### Expected Behavior

The quest copies do not appear.

### Version

0.0.3

### Mod Loader Version

1.20.1, 0.14.21

### Mod Loader

Fabric

### Logs or additional context

The bug was introduced in 0.0.3.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
are you sure you didnt add the quest to the other groups, because we allow the placement of the same quest in other groups to allow for better flow of quests

**Comment by realBritakee** [comment]
got the same issue https://i.imgur.com/6NeD19z.png it appears in every chapter

**Comment by lumiscosity** [comment]
> are you sure you didnt add the quest to the other groups, because we allow the placement of the same quest in other groups to allow for better flow of quests

yes, these ghost copies are automatically created in all other groups (and are automatically added to all newly made groups) and cannot be moved
