### ISSUE TITLE
[Bug]: 1.20 hVers0.0.3

### ISSUE THREAD

**Issue by drakosoldier298** [terrarium-earth/hercules#37]
### Bug Description

Heracles 0.0.3 complains of mitchmatched mod from server https://mclo.gs/gn7dLvW

### How to Reproduce?

install heracles on client and server
join server

### Expected Behavior

Join server without a popup kicking me back to main menu

### Version

0.0.3

### Mod Loader Version

0.14.21

### Mod Loader

Fabric

### Logs or additional context

 https://mclo.gs/gn7dLvW

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
the server is using 0.0.2 not 0.0.3

**Comment by drakosoldier298** [comment]
it isnt. 
![image](https://github.com/terrarium-earth/Heracles/assets/30358222/79cf05b9-fa11-4e1b-8335-bc266d3f43f2)
![image](https://github.com/terrarium-earth/Heracles/assets/30358222/27962b58-9f3c-4414-bc8b-b4a5a36bb6e3)

**Comment by drakosoldier298** [comment]
i... was editing the wrong server.
