### ISSUE TITLE
[Bug]: installed 0.0.4 and my quests didnt show

### ISSUE THREAD

**Issue by realBritakee** [terrarium-earth/hercules#41]
### Bug Description

i updated to the latest version and i copied all fiels from my save to the new created 0.0.4 heracles folder but when i start the game and open the book nothing is shown.

### How to Reproduce?

1. install heracles 0.0.4
2. use my heracles config files and start the game
3. open quest book and see

### Expected Behavior

[heracles.zip](https://github.com/terrarium-earth/Heracles/files/11788958/heracles.zip)

### Version

0.0.4

### Mod Loader Version

1.20.1 Latest

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by SirEdvin** [comment]
So, I have same issue in single player and only `/reload` command helps.
