### ISSUE TITLE
[Bug]: Crash on loading server

### ISSUE THREAD

**Issue by LempekPL** [terrarium-earth/hercules#42]
### Bug Description

When I start server when it loads Heracles it crashes

### How to Reproduce?

1. Install forge server
2. Run server with heracles and resourcelib
3. Server crashes

### Expected Behavior

no crash

### Version

0.0.4

### Mod Loader Version

1.20.1 - 47.1.3

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/8qjJcxHW

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Fixed in 0.0.5
