### ISSUE TITLE
[Bug]: Data not saving

### ISSUE THREAD

**Issue by HavocStudio2** [terrarium-earth/hercules#45]
### Bug Description

Issue with the quest not saving the data, I have been messing around with it and found out that after the 3rd quest and you try to link the quest up and change the icon background and icon close out of the menu and reopen it, it does not save the changes. This is also with the mod that you gave me.

### How to Reproduce?

1. Create a new quest/Fill out the data for that quest
2. Create another quest/ect
3. Create another quest/ect
4. Now change the icon of the 3 quest and link 1 with 2 and 2 with 3
5. Change the background of the quest
6. Close out the quest and reopen
7. This should of reproduce the issue

### Expected Behavior

Quest not saving

### Version

1.20.1-0.0.7-beta1

### Mod Loader Version

47.1.4 Forge 1.20.1

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/cendRAA3

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
I just did this exact thing and it worked perfectly fine

**Comment by ThatGravyBoat** [comment]
create and send a video of this happening

**Comment by HavocStudio2** [comment]
https://youtu.be/WjotHo4brNI

**Comment by ThatGravyBoat** [comment]
You almost always open lan when you test can you try not opening lan and seeing if the problem persists

**Comment by HavocStudio2** [comment]
> You almost always open lan when you test can you try not opening lan and seeing if the problem persists

The video was with no lan

**Comment by ThatGravyBoat** [comment]
oh ok interesting, I cant reproduce it myself there has to be something missing that causes it then

**Comment by HavocStudio2** [comment]
> oh ok interesting, I cant reproduce it myself there has to be something missing that causes it then

Can you show me a video of what you may be doing different?

**Comment by nvb-uy** [comment]
Happened the same to me. Seems like to save it you have to switch the edit mode and then click the x instead of esc, or at least using that method the quests were saved
