### ISSUE TITLE
[Feature Request]: Change maximum bounds to something bigger than 1000

### ISSUE THREAD

**Issue by nvb-uy** [terrarium-earth/hercules#48]
### Bug Description

GIF Preview:
https://cdn.discordapp.com/attachments/1126927836750557235/1136042569776762901/javaw_4mm32DYpRr.gif

### How to Reproduce?

1. Open the questbook
2. Open a group with a fair size (~100 quests or more)
3. Try to go to the bottom of the questline

### Expected Behavior

It's expected to be able to go to the bottom of the questline

### Version

0.0.6

### Mod Loader Version

1.20.1 - 0.14.21

### Mod Loader

Fabric

### Logs or additional context

1920x1080 - GUI Scale 3

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
This is not really a bug but more of that the restriction I set was 1000x1000 but Odysseus goes out side of those bounds as FTB allows you to place anywhere
