### ISSUE TITLE
[Bug]: different canvas borders depending on game resolution

### ISSUE THREAD

**Issue by wanesty** [terrarium-earth/hercules#5]
### Bug Description

The Quest net "canvas" is getting cropped depending on the resolution of the window see the following screenshots with the same quest tree but on different resolutions :

- 2560x1380
![2023-06-11_08 16 54](https://github.com/terrarium-earth/Heracles/assets/98633588/5f84a8d6-cb9a-4981-ab3b-ab8c33207265)

- 1777x1010
![2023-06-11_08 17 09](https://github.com/terrarium-earth/Heracles/assets/98633588/1b711377-4308-4e94-8434-9200dc91f1cb)

- 1068x608
![2023-06-11_08 16 59](https://github.com/terrarium-earth/Heracles/assets/98633588/1d4a1c81-0b79-4b1c-adab-505fd9bdeca6)

### How to Reproduce?

Create a task and move it to the top left at a high resolution, then display it on at a lower resolution. 

### Expected Behavior

The top left origin should be the same no matter the resolution. 

### Version

0.0.0

### Mod Loader Version

1.20

### Mod Loader

Quilt

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by wanesty** [comment]
Also the view does not go to the top left when closing and starting the game again, so i'm assuming it is using a center rather than a top left point.

In either case, it would be nice to have a tiny point marking the center, and maybe even a toggleable grid to align quests better, would be great if said grid had a magnetism for even better alignment !

**Comment by ThatGravyBoat** [comment]
yes it is a center pointed alignment the center of the box with the quests is 0,0 I will likely plan on adding a thin grid line from the center in all descriptions to show this point
