### ISSUE TITLE
[Bug]: Gather tasks don't work

### ISSUE THREAD

**Issue by nvb-uy** [terrarium-earth/hercules#50]
### Bug Description

After converting a group from FTB Quests using Odysseus, gathering quests don't work. After the player gets the item, the task will still say 0/1.

### How to Reproduce?

1. Convert group using Odysseus
2. Try to complete an item gathering task
3. Task will not be completed even if the items are gathered

Alternatively:

1. Convert group using Odysseus
2. Edit a quest's task to gather an item
3. Task will not be completed even if the items are gathered

### Expected Behavior

Task should be completed when the item(s) are gathered

### Version

0.0.6

### Mod Loader Version

1.20.1 - 0.14.21

### Mod Loader

Fabric

### Logs or additional context

Used Odysseus tool

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
can you send me the quest that has this issue please

**Comment by ThatGravyBoat** [comment]
Fixed it was an issue where an old dependency was kept in the quest file
