### ISSUE TITLE
[Feature Request]: Repeatable Tasks

### ISSUE THREAD

**Issue by Matiam0** [terrarium-earth/hercules#54]
### Is your feature request related to a problem?

No.

### Solution(s)

A system in which the player may repeat a task and get the reward.

### Mod Version

1.0.1

### Mod Loader Version

47.1.44

### Mod Loader

Forge

**Comment by gardenappl** [comment]
A configurable cooldown would be nice for this. Maybe even a command to "re-unlock" a quest? Then a datapack could re-unlock a quest with a function based on some criteria.

**Comment by Matiam0** [comment]
The mod could even track things using a hidden scoreboard.
