### ISSUE TITLE
[Bug]: Failed Deleted Quest

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [terrarium-earth/hercules#59]
### Bug Description

Mod fails to delete quest fully.

### How to Reproduce?

1. create quest
2. check quest file is made in your file system
3. now go into game and delete the quest
4. the quest is gone in game, but go back to your file system
5. the quest file is there
6. reload in game, the quest is back in game

### Expected Behavior

The quest's file being deleted.

### Version

1.0.1

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Fixed in next version
