### ISSUE TITLE
[Feature Request]: HOME/END/DEL behaviour in editor

### ISSUE THREAD

**Issue by sisby-folk** [terrarium-earth/hercules#61]
### Is your feature request related to a problem?

When i'm using the editor, I'd like to be able to more easily edit and navigate each line.

### Solution(s)

HOME should move to the start of the line, instead of the start of the file.
END should move to the end of the line, instead of the end of the file.
DEL should delete the character right of the cursor, instead of doing nothing.

### Mod Version

1.0.3

### Mod Loader Version

1.20.1 - 0.19.2

### Mod Loader

Quilt

**Comment by ThatGravyBoat** [comment]
Fixed
