### ISSUE TITLE
[Feature Request]: Allow create quest only CJK character

### ISSUE THREAD

**Issue by SettingDust** [terrarium-earth/hercules#63]
### Is your feature request related to a problem?

I can't create a task with only these characters. But I can create it with two letter and edit the quest name at sidebar to only CJK chars.
![图片](https://github.com/terrarium-earth/Heracles/assets/19922286/c4957d41-313f-434c-9e68-a85b130b1554)
![图片](https://github.com/terrarium-earth/Heracles/assets/19922286/9b874396-8516-4b5e-bf67-cfecad51c3d4)
![图片](https://github.com/terrarium-earth/Heracles/assets/19922286/8f6204ee-b1c5-46b0-9dd8-925c17de9647)

### Mod Version

1.0.4

### Mod Loader Version

1.20.1 0.20.1

### Mod Loader

Quilt

**Comment by ThatGravyBoat** [comment]
Quest id are the identifier used for the file system they must be file system compatible and as such they only allow `a-zA-Z_-` as those are all the common characters between all file systems allowed characters in file names

**Comment by ThatGravyBoat** [comment]
It is only used as an identifier and can not be seen a user

**Comment by SettingDust** [comment]
But I can actually input CJK characters and the file name is contains CJK. Need restrict I think

**Comment by ThatGravyBoat** [comment]
your file system may allow CJK characters but not all do, I have to make sure that it works on most systems as such restricting the characters allowed in an identifier that is used for a file name is what I do and will continue doing.

**Comment by SettingDust** [comment]
> your file system may allow CJK characters but not all do, I have to make sure that it works on most systems as such restricting the characters allowed in an identifier that is used for a file name is what I do and will continue doing.

Ya. So, adding a restrict to the input box is needed, isn't it?
