### ISSUE TITLE
[Bug]: Crafting quests don't complete properly

### ISSUE THREAD

**Issue by PiitchyB** [terrarium-earth/hercules#64]
### Bug Description

After fulfilling the requirements to complete a crafting quest, the task says completed, but the quest stays unfinished.

### How to Reproduce?

1. Create a quest that requires a recipe to be crafted
2. Craft said recipe
3. Check the quest's 'Task' tab and notice that it's 100%
4. Also notice that the quest itself is not complete
![image_2023-08-31_000440169](https://github.com/terrarium-earth/Heracles/assets/63941021/289ae794-fbd7-4809-b89b-586155f4af87)
![image_2023-08-31_000456530](https://github.com/terrarium-earth/Heracles/assets/63941021/cc513661-3dc5-4d05-ac33-e78b35dc8537)

### Expected Behavior

Expected to be able to complete the quest properly when all conditions are fulfilled.

### Version

1.0.4

### Mod Loader Version

1.20.1 - 47.1.44

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by bellebucane** [comment]
i am also having this problem, the item is crafted but i have no way of submitting or detecting the item to complete the task

**Comment by sisby-folk** [comment]
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/2cebd060-5f93-4bfc-903d-88bffb09de18)

On the main commit, I can't replicate this issue -  once 1.0.6 (or 1.1, idk what it'll be called) is out, check this issue again.

**Comment by ThatGravyBoat** [comment]
This was fixed in https://github.com/terrarium-earth/Heracles/commit/3160cb3e5c30872820964f061b10423d4a62f10a
