### ISSUE TITLE
[Bug]: Task and Reward Grammar

### ISSUE THREAD

**Issue by sisby-folk** [terrarium-earth/hercules#75]
Edit: Mostly complete via #76! see comment.

### Bug Description

The language used in in task/reward UI elements contains a good chunk of problems to resolve. 

I'll describe each issue I've encountered and solutions i consider reasonable.

I'll note I'm suggesting a lot of removal of pluralization for arbitrary strings, which i feel just isn't possible in a modded context.

---

1- Inappropriate pluralization for KillEntityTask
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/5ff580e3-c009-4abe-b260-972a2ef3a37a)
Suggested Title: `Kill: %s` - "Kill: Drowned", "Kill: Creeper"
Suggested Desc: `Kill %sx %s` - "Kill 15x Drowned", "Kill 15x Creeper"

---

2- Inappropriate pluralization for GatherItemTask
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/24c8ea75-12c4-4ca3-a4ae-454c6bea538b)
Suggested Title: `Acquire: %s` - "Acquire: Wheat Seeds"  "Acquire: Fishing Rod" "Acquire: Pumpkin"
Suggested Desc: `Acquire %sx %s` - "Acquire 32x Wheat Seeds"  "Acquire 1x Fishing Rod" "Acquire 8x Pumpkin"
(I'm suggesting "acquire" as "gather" is less intuitive for crafted items like fishing rods.)

---

3- Inappropriate pluralization for ItemReward

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/db9b080e-0a3b-40d3-9516-12edc589f349)

Suggested Title: `Receive: %s` - "Receive: Leather Boots" "Receive: Bread" "Receive: Torch"
Suggested Desc: `Receive %sx %s` - "Receive 1x Leather Boots" "Receive 10x Bread" "Receive 32x Torch"

---

4- Handling of Tags for GatherItemTask
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/6736d878-cd11-4a89-b4cb-590c8a869022)
Suggested Title: `Acquire any %s` - "Acquire any Swords" "Acquire any Stone Tool Materials"
Suggested Desc: `Acquire %sx of any %s` - "Acquire 1x of any Swords" "Acquire 11x of any Stone Tool Materials"

---

5- Unclear wording in CheckTask
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/17f85b7a-18a8-4e24-80f9-2c88a6223c2f)
Suggested Desc: `Click the check button to complete`
Suggested Button Tooltip: `Complete Task` (was "Check Task")
Reasoning: The button has a green check icon in it when it's both pressed and unpressed, so the analogyto "checking a box" is a bit far off. "Check" in the old tooltip may ambiguously mean "Inspect" - "Check off" is more explicit, but is less direct than complete.

--- 

6- Handling of XpQuestReward

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/e463dce7-0517-4cac-b6e5-efb7b2e70a02)
Suggested Title: `Receive: XP`
Suggested Desc: `Receive %s XP %s` - "Receive 50 XP points" "Receive 1 XP level"
In this case, pluralization can be used as the words ("point" and "level") are known. This is similar to what XpTask does.

--- 

7- Handling of LootTableReward

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/3cde67f6-5d7e-49a2-9d82-a7f97a5801d1)
Suggested Title: `Receive Random Loot`
Suggested Desc: `From %s` - "from minecraft:chests/bastion_other"

---

8- Handling of `Consume` GatherItemTasks
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/21361336-63b6-4a6b-a8dc-2124b9c5d6b3)
Suggested Title: `Submit: %s` - "Submit: any Saplings" "Submit: Dirt"
Suggested Desc: `Submit %sx %s` - "Submit 32x of any Saplings" "Submit 1x Dirt"
Suggested Button Text: `Submit Items`
Suggested Button Text: `Consumes %s Items` - "Consumes 32 Items"
Suggested Editor Options: `acquire`, `submit`, `submit_auto` (was `automatic`, `manual`, `consume` respectively)

(Side note - XP tasks seem to act as `submit_auto` with no options - submitted as #74) 

---

9- Handling of StatTask
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/2c3453fe-50a9-4700-a72e-6084bcb8b8b8)
Suggested Title: `Increase %s Stat` - "Increase Jumps Stat" "Increase Time Played Stat" "Increase Distance By Horse Stat"
Suggested Desc: `Reach a %s stat of %s` - "Reach a Jumps stat of 20" "Reach a Time Played stat of 1" "Reach a Distance By Horse Stat of 5000"

---

10- Control Hints for InteractTasks

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/23e44395-9df7-429e-b0fd-49068cebf4ec)

This `[Right-Click]` is hardcoded, which doesn't match the game logic. If it _wasn't_ hardcoded, it might read `[p] the Entity` when rebound to p.
Suggested Desc: `Use [%s] to interact`
Alternate Suggested Desc: None! I don't think a control hint for "interact" is an appropriate `desc` value.

---

11- Handling of Advancements

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/6ac75400-d799-4547-a9d0-785ab1d5c65b)

Suggested Title: `Complete an Advancement`
Suggested Desc: `Achieve '%s'` - 'Achieve 'Hot Stuff'`
Reasoning: No other task type uses a run-on sentence like this (closest is our suggestion for loot tables).

---

12- Consistency of information density in titles and descriptions

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/6131689d-af4c-4e22-910d-9e4407a2d35b)
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/d8a72ddf-01c2-4a47-a583-a2ae18074d45)

Ideally, "title" summarises the type of task expected, and "desc" defines the full required task -and similar with rewards.
This is true of GatherItemTask, KillEntityTask, ItemReward, CommandReward, LootTableReward, XPTask, DimensionTask, and CheckTask - as well as revisions above for XPQuestReward and StatTask.

However, some other task type use the `desc` field for "hints" (ItemInteract, BlockInteract, and EntityInteract), or for the complete opposite - providing _less_ information than the title (BiomeTask, RecipeTask, and StructureTask)

The Less information -> More information relationship should ideally be consistent. 
Suggested Titles: "Visit Biome", "Craft Recipe", and "Find Structure"
Alternate Suggested Titles: None! Just use the description as the title, and have no description.

---

### Additional Context

I've kept solutions in the current format, but I do also think that having a title, description, progress bar, _and_ numeric indicator is often taxingly redundant for many reward/task types. Compressing the description and title into one title (used as the description if a custom title is added ala #65) would resolve a lot of this.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by sisby-folk** [comment]
giving this a go in a fork now!

**Comment by acikek** [comment]
I'd refrain from using the word "achieve" to describe completing an advancement. There's a lot of verb repetition already, so to keep it consistent, I think the description for that should just be "Complete 'Hot Stuff'".

**Comment by sisby-folk** [comment]
With #76 merged now this is mostly complete. I'm going to cover the leftovers in this comment for clarity:

---

**1) Pinned Task Titles**

![271199834-fdc35197-eb4f-466f-a073-413aa932312f](https://github.com/terrarium-earth/Heracles/assets/55819817/bda23f8c-de74-4f88-b502-af3114d1fe4e)

Some pinned tasks have the same title for every instance of task type. Fixes as follows:

 - Complete an advancement -> Complete '{title}' (the plural variant can stay as is)
 - Submit XP -> Submit XP Levels / Submit XP Points
 - Craft a Recipe -> Craft '{recipeId}'

These changes **shouldn't** change the way the title and desc are formatted in the task view.
In a pinch, deliberately not using title formatters in task widget and then using them for this could work, you'd just have to misuse the pluralness condition a bit for e.g. points/levels.

---

**2) Type-only Redundant Task Titles**

Some task titles that are the exact same for all tasks of that type. I think this could be avoided by just allowing these tasks to not have descriptions unless they actually need them. This should help with both pinned tasks and potentially custom task titles, as the new "title" can be used as a description instead.

| Case | Title | Description | Progress |
|--------|--------|--------|---|
| Current Format | Craft a Recipe | Craft minecraft:wooden_pickaxe | 0/1
| New w/ No Custom Title | Craft minecraft:wooden_pickaxe |  | 0/1
| New w/ Custom Title | Craft a Wooden Pickaxe | Craft minecraft:wooden_pickaxe | 0/1

---

**3) CollectionType Should Be Translatable**

Translations are important modpack devs too! I'd suggest these:

 - `Acquire` or `Gather` - currently called "automatic", the mode where items are not consumed.
 - `Submit` - currently called "manual", the mode where you click a button to consume the items.
 - `Auto Submit` - currently called "consume", the mode where items are instantly consumed when you meet the target.

**Comment by ThatGravyBoat** [comment]
Shouldnt this be all good now since if there is a mistake the title can be overridden?

**Comment by sisby-folk** [comment]
Yep what I'll do is I'll close this one and open a new ticket for pinned quests.
