### ISSUE TITLE
[Bug]: Sound spamming in composite quests

### ISSUE THREAD

**Issue by LZ1WS** [terrarium-earth/hercules#81]
### Bug Description

When you complete a composite quest with two OR goals in it, it spazzes out and starts spamming you with notifications about completion

### How to Reproduce?

1. Create composite quest with two items (gathering)
2. Obtain that item
3. Get spammed by notifications and sounds
4. Eargasm

### Expected Behavior

One time notification upon completion

### Version

1.0.5

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by LZ1WS** [comment]
It's also happened with regular quest, it seems that it happens with new quests sometimes, I just joined a world and got blasted by unlock sound of a quest that I couldn't get before due to it's late addition

**Comment by bluebear94** [comment]
I can’t reproduce this on 05a40ea.

**Comment by SubordinalBlue** [comment]
I _can_ reproduce this, reliably, on release 1.1.0.
If I complete any composite task it will happen, whether or not the task uses vanilla items or fancy ones with nbt.
[any_vanilla.json](https://github.com/terrarium-earth/Heracles/files/13325019/any_vanilla.json)
