### ISSUE TITLE
[Feature Request]: Option for Displaying Multiple Icons for a single Quest

### ISSUE THREAD

**Issue by SubordinalBlue** [terrarium-earth/hercules#87]
A quest may have a number of item tasks, or even one composite task that can be satisfied by one of a number of items; it would be nice to be able to have a quest's icon rotate among several items.

Yes, I am thinking of how that looks in FTBQ. However, FTBQ makes assumptions to select what icons to show.
It would be better, imho, to have the quest author make that choice explicitly.

### Mod Version

0.5.0

### Mod Loader Version

0.14.22

### Mod Loader

Fabric

**Comment by sisby-folk** [comment]
I wanna expand on this one - I mentioned this in our PR, but I think that the concept of an icon as used by quests, tasks, and rewards, should be generified into an expansion of what is currently `QuestIcon` - so we can have things like `ItemIcon` (currently ItemQuestIcon), but then also `ItemTagIcon` (GatherItemTask), `BlitIcon` (CheckTask), `EntityIcon` (KillEntityTask), etc. 

That way, even if making a UI for editing something like this might be annoying, it could be easily achieved editing quest data manually.

**Comment by ThatGravyBoat** [comment]
This can be closed because of https://github.com/terrarium-earth/Heracles/commit/0fee1f0f88155f0da59946c42cdd3adb0df4b4be, a new issue has been opened for additional quest icon types.
