### ISSUE TITLE
[Bug]: FIrst letter you type in any Heracles text field is sometimes unbackspaceable

### ISSUE THREAD

**Issue by WatermelonFroggy** [terrarium-earth/hercules#89]
### Bug Description

Hello! I've come across this issue so many times, its not that big of a deal but its super annoying to deal with.
Occasionally whenever you type anything in the first letter is usually unremoveable.

### How to Reproduce?

1. Do anything that requires you to type like making a new quest.
2. Type
3. Try to backspace the first letter and be unable to

### Expected Behavior

expected behavior: Be able to backspace the first letter of the word.

### Version

1.0.5

### Mod Loader Version

1.20.1 - 47.1.3

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by gardenappl** [comment]
The way I understand it, the mod considers empty quest names/tooltips/etc to be illegal, so it won't let you have an empty text field for these. So if you want to erase and replace all text, then you have to 

1. erase every letter except the first one
2. type what you want
3. erase first letter

This is annoying and counter-intuitive but at least has a workaround.

**Comment by ThatGravyBoat** [comment]
I have not been able to reproduce this in dev and I just released 1.1.0 so if you can test it in there that would be great!
