### ISSUE TITLE
[Feature Request]: Escape going back to previous page instead of closing out entirely

### ISSUE THREAD

**Issue by WatermelonFroggy** [terrarium-earth/hercules#90]
### Is your feature request related to a problem?

This has been an issue that has been plaguing me since I started using this mod.
My issue is that when you press escape it closes out the entire GUI instead of just going back!

### Solution(s)

Make it so that when you press escape instead of completely closing the guI it only goes back.

### Mod Version

1.0.5

### Mod Loader Version

1.20.1 - 47.1.3

### Mod Loader

Forge

**Comment by cutiexe** [comment]
Seconding this request. We at least need a keybind that can move back a page instead of trying to hit the very small click target in the corner.

**Comment by lonevox** [comment]
I think Alt + ← for going back to the quest book and Alt + → for going forwards to the last opened quest would work well too. These keybinds are the standard for backwards and forwards, which many mice with additional buttons are pre-bound with, so you'd be able to more easily navigate the quests with the mouse.
