### ISSUE TITLE
[Bug]: Non-edit bounds for the quest screen are totally wrong, making it unusable

### ISSUE THREAD

**Issue by sisby-folk** [terrarium-earth/hercules#91]
### Bug Description

A video explains this best: 

https://github.com/terrarium-earth/Heracles/assets/55819817/2b3eaef7-1018-4e8a-a589-5c854ff36292

### Version

1.0.5

### Mod Loader Version

0.20.2

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
The way the sizing works is in edit the size is 500 radius when not editing the bounds are min max -+ 100 so I have no idea how this would happen, and I never ran into it while testing...

**Comment by sisby-folk** [comment]
Through the magic of a logger!

`The Basics: X -52...372 Y -180...164`

This should mean that the furthest left quest is X `48`, and the furthest right quest is X `272`

Here's two basics quests:

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/b5c1817c-9294-4a7b-aa0b-541b532ce708)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/840bad8d-f32b-414d-9570-9e0774d8ec20)

So, hmm, the bounds calc is definitely off, right?

**Comment by sisby-folk** [comment]
Through the magic of an extra logger:

`Xs [48, 176, 48, 48, 48, 272, 176, 272, 176]`

So, only the visible quests are used, which does make some sense.

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/0ffca9ea-f23f-49e1-8c1e-aa343f0878f1)

![image](https://github.com/terrarium-earth/Heracles/assets/55819817/69b1b3dc-eee9-414b-b6ef-866a813350d3)

That would figure that the bounds are actually pretty correct, but that the way it's being used isn't - that 100 unit buffer should make finders keepers fit comfortably on-screen.

[heracles.zip](https://github.com/terrarium-earth/Heracles/files/12837062/heracles.zip)

**Comment by sisby-folk** [comment]
![image](https://github.com/terrarium-earth/Heracles/assets/55819817/dd808c80-a5f1-4347-bddc-17e7d881a86e)

yeah cool i figured it out. it's backwards.

Offset x+ moves the screen _left_, which would be fine, but the bounds are calculated as if it moves it right.

**Comment by sisby-folk** [comment]
popped a tiny solution it on the end of the other PR, seeing as it's nothing special or proper.
