### ISSUE TITLE
[Bug]: HTML headings in quest descriptions don't wrap

### ISSUE THREAD

**Issue by SubordinalBlue** [terrarium-earth/hercules#98]
### Bug Description

In the screen shot the sample sentence is repeated four times.
The first two repetitions are inside `<H1>` (first line) and `<H2>` (second line) tags.
The third and fourth repetitions are on one line, without any html tags.

![2023-10-14_12 48 28](https://github.com/terrarium-earth/Heracles/assets/6677700/9a63ab62-85ce-40ef-bd49-7ae2936408fc)

### Version

0.5.4

### Mod Loader Version

0.14.22

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
This needs to be reported to the hermes repo https://github.com/terrarium-earth/Hermes

**Comment by SubordinalBlue** [comment]
Ah ha. Looks like someone has already reported this to that repo.

TY, bluebear94.
